"""Add security features

Revision ID: 585e5190e360
Revises: 030acb7010d8
Create Date: 2025-07-27 01:44:39.158296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585e5190e360'
down_revision = '030acb7010d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
